const photoList = [
  {
    id: 0,
    photoName: "Café citrouille",
    description: "hhzhhzzhzhhrt",
    prix: 0,
    imgSrc: "./assets/photo0.jpg",
    like: 0,
  },
  {
    id: 1,
    photoName: "Café licorne",
    description: "hzzhhthtzzhtddrshhshh",
    prix: 10,
    imgSrc: "./assets/photo1.jpg",
    like: 0,
  },
  {
    id: 2,
    photoName: "",
    description: "",
    prix: 9,
    imgSrc: "./assets/photo2.jpg",
    like: 0,
  },
  {
    id: 3,
    photoName: "",
    description: "",
    prix: 8,
    imgSrc: "./assets/photo3.jpg",
    like: 0,
  },
  {
    id: 4,
    photoName: "",
    description: "",
    prix: 7,
    imgSrc: "./assets/photo4.jpg",
    like: 0,
  },
  {
    id: 5,
    photoName: "",
    description: "",
    prix: 6,
    imgSrc: "./assets/photo5.jpg",
    like: 0,
  },
  {
    id: 6,
    photoName: "",
    description: "",
    prix: 5,
    imgSrc: "./assets/photo6.jpg",
    like: 0,
  },
  {
    id: 7,
    photoName: "",
    description: "",
    prix: 4,
    imgSrc: "./assets/photo7.jpg",
    like: 0,
  },
  {
    id: 8,
    photoName: "",
    description: "",
    prix: 3,
    imgSrc: "./assets/photo8.jpg",
    like: 0,
  },
  {
    id: 9,
    photoName: "",
    description: "",
    prix: 2,
    imgSrc: "./assets/photo9.jpg",
    like: 0,
  },
];

export default photoList;
